---
layout: post
title: "Starting with Data"
date:   2015-1-26 20:49:52
authors: "FirstName LastName, FirstName LastName"
dateCreated:  2014-11-26 20:49:52
lastModified: 2015-07-23 14:28:52
category: time-series-workshop
tags: [module-1]
mainTag: GIS-Spatial-Data
description: "This post explains the fundamental principles, functions and metadata that you need to work with raster data in R."
code1:
image:
  feature: lidar_GrandMesa.png
  credit: LiDAR data collected over Grand Mesa, Colorado - National Ecological Observatory Network (NEON)
  creditlink: http://www.neoninc.org
permalink: /R/Raster-Data-In-R/
code1: /R/2015-07-22-Introduction-to-Raster-Data-In-R.R
comments: true

---

<section id="table-of-contents" class="toc">
  <header>
    <h3>Contents</h3>
  </header>
<div id="drawer" markdown="1">
*  Auto generated table of contents
{:toc}
</div>
</section><!-- /#table-of-contents -->

##About
This activity will walk you through the fundamental principles of working
with raster data in R.

**R Skill Level:** Intermediate - you've got the basics of `R` down.

<div id="objectives">

<h3>Goals / Objectives</h3>
After completing this activity, you will know:
<ol>
Understand the types of questions we’re going to be focusing on
Know about the site we’re looking at- introduce Harvard Forest site
Understand what file types we’ll be working with
Understand the Geotiff format
Understand shp files
Understand dbf files - exchange format for vector files
csv files
Understand what metadata are
Understand that spatial data are generally available on web sites via some download protocol
Understand that metadata come in many forms and you have to capture them
</ol>

<h3>Things You'll Need To Complete This Lesson</h3>

<h3>R Libraries to Install:</h3>
<ul>
<li><strong>raster:</strong> <code> install.packages("raster")</code></li>
<li><strong>rgdal:</strong> <code> install.packages("rgdal")</code></li>

</ul>
<h4>Tools To Install</h4>

Please be sure you have the most current version of `R` and preferably
R studio to write your code.


<h4>Data to Download</h4>

Download the raster and *in situ* collected vegetation structure data:
<ul>
<li><a href="http://neonhighered.org/Data/LidarActivity/CHM_InSitu_Data.zip" class="btn btn-success"> DOWNLOAD Sample NEON LiDAR data in Raster Format & Vegetation Sampling Data</a></li>
<li><a href="{{ site.baseurl }}/data/rasterLayers_tif.zip" class="btn btn-success"> DOWNLOAD NEON imagery data (tiff format) California Domain 17 (D17)</a></li>
</ul>

<p>The LiDAR and imagery data used to create the rasters in this dataset were
collected over the San Joaquin field site located in California (NEON Domain 17)
and processed at <a href="http://www.neoninc.org" target="_blank" >NEON </a>
headquarters. The entire dataset can be accessed by request from the NEON website.</p>  

<h4>Recommended Pre-Lesson Reading</h4>
<ul>
<li>
<a href="{{ site.baseurl }}/GIS-Spatial-Data/Working-With-Rasters/" target="_blank">
The Relationship Between Raster Resolution, Spatial extent & Number of Pixels - in R</a>
</li>
<li>
<a href="http://cran.r-project.org/web/packages/raster/raster.pdf" target="_blank">
Read more about the `raster` package in R.</a>
</li>
</ul>
</div>

## Questions to ask of spatial data

There are many types of questions that can be addressed with spatial data.

We're interested in the Harvard Forest site. It's a NEON site that has been monitored for about 40 years. There's a lot of different data available for this site, over time and space.

-- add Harvard forest site link

We would like to create the following outputs to better understand our project.
- Plots of temperature, precipitation, PAR and daylength over the 2 year time period (metrics which are related to the greening and browning of plants)  compared to NDVI (greenness).
- Basemaps of her site showing
- The location of the tower that measured the above variables and imagery showing what the site look like.
- tree height
- Topography
- A time series animation of NDVI for both sites that she can post on her blog.

### File types

We'll be working with raster and vector files that have different sets of measurements.

**Raster data**  
The raster data we'll be using are Geotiff.

It has the data itself in the grid as well as the coordinate reference system stored in the same file.

You have to access this data with particular tools - you can't look at it like a regular tiff. When you do access it, you can see that the coordinate information is like this:

```
dimensions  : 1367, 1697, 2319799  (nrow, ncol, ncell)
resolution  : 1, 1  (x, y)
extent      : 731453, 733150, 4712471, 4713838  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=18 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0
values      : 0, 1098.62  (min, max)
```

resources:
Finding Data
DataOne - www.dataone.org/find-data
Government / Federal Agency data:
www.data.gov/
www.geoplatform.gov/
State and local data, such as : www.data.ny.gov/
ecologicaldata.org
Finding/reading metadata:
https://www.fgdc.gov/metadata
http://geology.usgs.gov/tools/metadata/tools/doc/faq.html
