---
layout: post
title: "Lesson 03: Key Spatial Metadata to Understand"
date:   2015-10-27
authors: [Dave Roberts, Tracy Teal, Kaitlin Stack Whitney, Leah Wasser, Megan A. Jones]
contributors: [ ]
dateCreated: 2015-10-23
lastModified: `r format(Sys.time(), "%Y-%m-%d")`
packagesLibraries: [ ]
category: [self-paced-tutorial] 
tags: [R, GIS-Spatial-Data, metdata-eml, informatics]
mainTag: spatial-data-management-series
description: "Add description here."
code1: CodeTitleSameAsFileName.R
image:
  feature: NEONCarpentryHeader_2.png
  credit: A collaboration between the National Ecological Observatory Network (NEON) and Data Carpentry
  creditlink: http://www.neoninc.org
permalink: R/EditLink
comments: false
---

{% include _toc.html %}

##About
Add description.

**R Skill Level:** Intermediate - you've got the basics of `R` down.

<div id="objectives" markdown="1">

#Goals / Objectives

After completing this activity, you will:

* 


##Things You’ll Need To Complete This Lesson
To complete this lesson: you will need the most current version of R, and 
preferably RStudio, loaded on your computer.

###Install R Packages

* **NAME:** `install.packages("NAME")`

* [More on Packages in R - Adapted from Software Carpentry.]({{site.baseurl}}R/Packages-In-R/)

###Download Data
EDIT AS NEEDED
{% include/dataSubsets/_data_Airborne-Remote-Sensing.html %}

****

{% include/_greyBox-wd-rscript.html %}

**Raster Lesson Series:** This lesson is part of a lesson series introducing
[spatial data and data management in `R` ]({{ site.baseurl }}tutorial/URL).
It is also part of a larger 
[spatio-temporal Data Carpentry Workshop ]({{ site.baseurl }}workshops/spatio-temporal-workshop)
that includes working with  
[raster data in `R` ]({{ site.baseurl }}tutorial/spatial-raster-series),
[vector data in `R` ]({{ site.baseurl }}tutorial/spatial-vector-series)
and  
[tabular time series in `R` ]({{ site.baseurl }}tutorial/tabular-time-series).

****

###Additional Resources
* Read more on coordinate systems in the
<a href="http://docs.qgis.org/2.0/en/docs/gentle_gis_introduction/coordinate_reference_systems.html" target="_blank">
QGIS documentation.</a>
* NEON Data Skills Lesson <a href="{{ site.baseurl }}/GIS-Spatial-Data/Working-With-Rasters/" target="_blank">The Relationship Between Raster Resolution, Spatial extent & Number of Pixels - in R</a>



</div>

##Intro to CRS
What is a coordinate system?
Tells you where you are on the surface of the Earth
To tell you where you are, you need three pieces of information
- ellipsoid, projection datum

Think about a globe of the earth. It's a 3D ellipsoid. You don't work with globes though, instead we work with maps, 2D representations of the earth or areas of the earth. To move from that 3D to the 2D representation, we need
to know certain things about how that projection was done.

You need to know what model of the earth you're using, (ellipsoid) how you've created your 2D map from the 3D earth (projection) and what's the central reference point of the map (datum).

When you're working with spatial data, you want all the maps that you're working with to employ the same coordinate system.

Lattitude and longitude is a coordinate system, because it does tell you where you are on the earth. But, because it's dealing with the 3D earth, it doesn't have a projection. It does have a datum, which is 0 longitude, 0 latitude, where the Prime Meridian and Equator meet.

Another unit system is Northings and Eastings, and this is often used with GPS units. In this coordinate system, the ellipsoid is WGS84 (link to WGS84 and/or a list of types), the projection is Universal Transverse Mercator (UTM) and the datum varies depending on where you are. In the US it's usually NAD83.

If you were at the Washington Monument in Washington DC for example, you would report your Northings and Eastings coordinates as:

XXX m North, YYY m East, UTM Zone 18
and that says that you're XXX m north and YYY m East of the zero point for Zone 18, which is the lower left of that zone.

Picture of the Washington monument in Zone 18

Once you know all this information, you can convert site location between coordinate systems.

###Proj vs EPSG

###What is projection (very very high level)

##Intro to EXTENT

###Units

###Extent in raster data (rasters are always rectangles / squares)

###vectors - extent represents the outermost boundary of vertices in the spatial shapefile.


