---
title: "R Packages for Spatial-temporal Data -- Setting Up Your Working Environment"
teaching: 30
exercises: 30
questions:
 - TBD
objectives:
 - TBD
keypoints:
 - TBD
source: Rmd
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
source("../setup.R")
knitr_fig_path("09-")
```


## About
Add description.

**R Skill Level:** Intermediate - you've got the basics of `R` down.


# Goals / Objectives

After completing this activity, you will:

*
* Understand that different spatial data types & associated file types require
different tools to work with them.

## Things You’ll Need To Complete This Lesson
To complete this lesson you will need the most current version of R, and
preferably, RStudio loaded on your computer.

### Install R Packages

* **NAME:** `install.packages("NAME")`

* [More on Packages in R - Adapted from Software Carpentry.]({{site.baseurl}}R/Packages-In-R/)

### Download Data
EDIT AS NEEDED


**Spatial-Temporal Data & Data Management Lesson Series:** This lesson is part
of a lesson series introducing
[spatial data and data management in `R` ]({{ site.baseurl }}tutorial/URL).
It is also part of a larger
[spatio-temporal Data Carpentry Workshop ]({{ site.baseurl }}workshops/spatio-temporal-workshop)
that includes working with  
[raster data in `R` ]({{ site.baseurl }}tutorial/spatial-raster-series),
[vector data in `R` ]({{ site.baseurl }}tutorial/spatial-vector-series)
and  
[tabular time series in `R` ]({{ site.baseurl }}tutorial/tabular-time-series).



### Additional Resources

* <a href="http://cran.r-project.org/web/packages/raster/raster.pdf" target="_blank">
Read more about the `raster` package in `R`.</a>
* <a href="http://neondataskills.org/R/Raster-Data-In-R/" target="_blank" >
NEON Data Skills: Raster Data in R - The Basics</a>
* <a href="http://neondataskills.org/R/Image-Raster-Data-In-R/" target="_blank" >
NEON Data Skills: Image Raster Data in R - An Intro</a>

</div>

## raster

## rgdal

## rastervis - time series plotting

## Set up working directory - <<link to working directory page??> 
